version: "2"

run:
  go: "1.25"
  timeout: 5m
linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck
linter-settings:
  stylecheck:
    checks:["all", "-ST1003", "", "-ST1016","-ST1020", "-ST1022",]

issues:
  max-issus-per-linter: 0
  max-same-issues: 0